version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sports-erp
    ports:
      - 5432:5432
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
