@startuml
allowmixing

left to right direction

actor "Admin" as admin

rectangle Usecases {
  usecase "Create user" as CU
  usecase "Update user" as UU
  usecase "Deactivate" as DU
  usecase "Authentication" as ATC
  usecase "Authorization" as ATR

  usecase "Create Access Group" as CAG
  usecase "Update Access Group" as UAG
  usecase "Delete Access Group" as DAG
  usecase "Find Access Group" as FAG
  usecase "Find Access Groups" as FAGS
}

rectangle Database {
  json Users {
   "id":"string",
   "name":"string",
   "email": "string",
   "document":"string",
   "role": "string",
   "password": "string",
   "isActive": "boolean",
   "tenantId": "string",
   "franchisesId": "JSON.type string[]",
   "accessGroupId": "string"
  }

  json AcessGroup{
    "id": "string",
    "name": "string"
  }

  json AcessGroupsResources{
    "accessGroupId": "string",
    "resourceId": "string"
  }

  json SystemResources {
   "id": "string",
   "name": "string",
   "module": "string",
   "createdAt": "datetime",
   "updatedAt": "datetime"
  }
}

admin --> Tenant

admin --> CU
admin --> UU
admin --> DU
admin --> ATC
admin --> ATR

admin --> CAG
admin --> UAG
admin --> DAG
admin --> FAG
admin --> FAGS

CU --> Database
UU --> Database
DU --> Database
ATC --> Database
ATR --> Database

CAG --> Database
UAG --> Database
DAG --> Database
FAG --> Database
FAGS --> Database

@enduml